[package]
name = "guessing_gane"
version = "0.1.0"
authors = ["yasuyuki <csya18003@g.nihon-u.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.0"